version: '3'

services:
  hugo:
    container_name: erwan_website
    build: .
    volumes:
      - ".:/src/"
      - "./output/:/output"
    environment:
      - HUGO_REFRESH_TIME=3600
      - HUGO_THEME=toha
      - HUGO_BASEURL=new.erwankessler.com
      - HUGO_WATCH=true
    ports:
      - 127.0.0.1:5056:443
    restart: always
